name: client_server_sockets
description: A simple client-server sockets package that uses the Socket and ServerSocket classes.
version: 1.0.0
repository: https://github.com/georges-ph/client_server_sockets
issue_tracker: https://github.com/georges-ph/client_server_sockets/issues

environment:
  sdk: ^3.2.0

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
